# Generated by Django 2.1.5 on 2019-02-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_survey_app', '0002_auto_20190208_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
