# Generated by Django 2.1.5 on 2019-02-18 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_survey_app', '0003_response_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userssurveys',
            name='user',
        ),
        migrations.AddField(
            model_name='userssurveys',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
